<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Budgetpedia API - Supporting informed debate about the Toronto budget</title>
	<meta name="description" content="Learn about Budgetpedia">
  	<meta name="keywords" content="Budget, Open Data, Toronto, Canada, Data Visualization, Public Policy">
  	<meta name="author" content="Budgetpedia, Rafi Chaudhury">
	<link rel="stylesheet" href="css/bootstrap.min.css">
	<link href="css/material.min.css" rel="stylesheet">
	<link rel="stylesheet" href="css/budgetpedia-apr2017.css">
	<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,500,700" type="text/css">
	<link rel="shortcut icon" href="img/budgetpedia-favicon.ico" type="image/x-icon">
	   <!-- Material Design Lite -->
	   <script src="https://code.getmdl.io/1.3.0/material.min.js"></script>
	   <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css">
	   <!-- Material Design icon font -->
	   <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
</head>

<body>
	<?php include 'nav-menu.php' ?>
	    <div class="page-content"> <!-- CONTAINER-FLUID excluded -->
	    		<div class="row padding-universal" id="site-header">
	    			<div class="col-sm-12">
	    					<div class="center vertical-center">
	    						<h1>Budgetpedia API</h1>
	    					</div>
	    			</div>
	    			<!-- COLUMN END -->
	    		</div> <!-- ROW END -->
				<div class="row padding-universal">
					<div class="col-sm-6">
						<h2 class="heading">About the API</h2>
						<p>The Budgetpedia API allows third party developers to access financial data for Toronto through a RESTful API interface. The example below allows generates charts for City expenses through HTTP GET requests.</p>

						<p>To view city expenses, select a budget category below:</p>
						<p>
							<select id="exp-categories" onchange="dropdownSelectVariable()">
							  <option value="DEFAULT">Select an option...</option>
							  <option value="CULTURE">Recreation & Cultural services</option>
							  <option value="ENVIRONMENT">Environmental Services</option>
							  <option value="GOVERNMENT">General Government</option>
							  <option value="HEALTH">Health Services</option>
							  <option value="HOUSING">Social Housing</option>
								<option value="LEGACY">Legacy Works & Agencies</option>
								<option value="PLANNING">Planning & Development</option>
								<option value="PROTECTION">Protection to Persons and Property</option>
								<option value="SOCIALSERVICES">Social & Family Services</option>
								<option value="TRANSPORTATION">Transportation Services</option>
							</select>
						</p>
						
					</div> <!-- COL END -->
					<div class="col-sm-6">
						<div id="container"></div>
						<div id="category-definition"></div>
					</div> <!-- COL END -->
				</div> <!-- ROW END -->

				<div class="row padding-universal">
					<div class="col-sm-12">
						<h2 class="heading">Example Request</h2>
						<p>The above example was generated by accessing the Budgetpedia API JSON endpoint and extracting object data into arrays. The arrays were used as series data in the charting framework Highcharts. Some example code is shown below.</p>

						<p>More Extensive Documentation will be available soon!</p>
					</div> <!-- COL END -->
					<div class="col-sm-6">
					<h3 class="heading">GET Request</h3>
<pre class="prettyprint">
//DECLARE VARIABLES
var i;
function dropdownSelectVariable(){
var dropdownSelect = document.getElementById("exp-categories").value;
var newArray = new Array();
var datesArray = new Array();

//ACCESS API ENDPOINT
$.getJSON('https://getbridgeapp.co/api/budgetpedia/torontoexpenses19982016', function(result) {
console.log(result)
// CONVERT DATA TO ARRAYS
for (var i = 0; i < result.length; i++){
if (result[i].category == dropdownSelect){
 newArray.push(result[i].amount_thousands);
datesArray.push(result[i].year);    
};
});
	</pre>

					</div> <!-- COL END -->

					<div class="col-sm-6">
						<h3 class="heading">Example JSON</h3>
<pre class="prettyprint">
	[
	    {
	        "category": "ENVIRONMENT",
	        "subcategory": "Environmental services",
	        "amount_thousands": 587061,
	        "year": 1998,
	        "definitions": null
	    },
	    {
	        "category": "GOVERNMENT",
	        "subcategory": "General government",
	        "amount_thousands": 593671,
	        "year": 1998,
	        "definitions": null
	    }
	]
</pre>
					</div>
				</div> <!-- ROW END -->
				<div class="row padding-universal" id="footer">
					<?php include 'footer.php' ?>
				</div> <!-- ROW END -->
			</div> <!-- CONTAINER END -->	
	    </div> <!-- PAGE CONTENT END -->
	  </main>
	</div>
		<script>hljs.initHighlightingOnLoad();</script>
		<script type="text/javascript" src="js/jquery-2.2.4.min.js"></script>
		<script type="text/javascript" src="js/material.min.js"></script>
		<script type="text/javascript" src="js/bootstrap.min.js"></script>
		<script src="js/highcharts.js"></script>
		<script src="js/modules.js"></script>
		<script src="js/exporting.js"></script>
		<script src="budgetpedia-api-beta.js"></script>
		<script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>

</body>
</html>